name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Harshithatla
          outputs: dist/snake.svg

      - name: Upload generated snake.svg as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/snake.svg

  deploy-snake:
    needs: generate-snake
    runs-on: ubuntu-latest

    steps:
      - name: Download generated artifact
        uses: actions/download-artifact@v4
        with:
          name: snake

      - name: Deploy snake.svg to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: output
