name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Harshithatla
          outputs: |
            dist/snake.svg

      - name: Commit snake.svg to main branch
        run: |
          mkdir -p .github/snake
          cp dist/snake.svg .github/snake/snake.svg
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/snake/snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
